image: ubuntu:14.04

stages:
  - build

build:
  tags:
    - 24604.s.t4vps.eu
  stage: build
  script:
    - apt-get -y update && apt-get -y install subversion build-essential gcc-arm-linux-gnueabi u-boot-tools
    - make CROSS_COMPILE=arm-linux-gnueabi- ARCH=arm uImage
  artifacts:
    untracked: true
    paths:
      - ./
